# Markdownlint configuration for AI Security Scanner
# See: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

# MD013: Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD024: Multiple headings with the same content
MD024:
  allow_different_nesting: true

# MD033: Inline HTML
MD033: false

# MD041: First line in file should be a top level heading
MD041: false

# MD046: Code block style
MD046:
  style: fenced
